#cloud-config
---
hostname: htb-search
system_info:
  default_user:
    name: sysadmin
    home: /home/sysadmin
    shell: /bin/bash
    lock_passwd: True
    gecos: sysadmin
    groups: [adm, cdrom, dip, lxd, sudo, wheel,www-data]


package_upgrade: true
# pip is required to install gdown, to download a backup of the config
packages:
    - nginx
    - php-fpm
    - pkg-php-tools
    - php-dev
    - redis

write_files:
${yamlencode(files)}

runcmd:
    - "echo Starting scripts"
    - "pecl install redis"
    - "echo \"extension=redis.so\" >> /etc/php/7.4/fpm/php.ini"
    - "mkdir -p /var/run/redis"
    - "usermod -g www-data redis"
    - "usermod -aG redis www-data"
    - "usermod -aG redis sysadmin"
    - "chown -R redis:redis /var/cache/redis"
    - "systemctl restart redis"
    - "systemctl restart nginx"
    - "systemctl restart php7.4-fpm"
